### ISSUE TITLE
Return 4XX or 5XX status code on failure

### ISSUE THREAD

**Issue by mestebangutierrez** [SmartDeveloperHub/gitlab-enhancer#8]
Up to now, whenever the service fails it returns a response with status code 200 and "false" as body.

When the service fails it should return a proper 4XX or 5XX status code depending on whether the failure is due to an incorrect client interaction or a problem within the service implementation.

**Comment by alejandrofcarrera** [comment]
This issue is fixed due to compatibility with Gitlab response.
Standard says something and people does other :)

**Comment by mestebangutierrez** [comment]
Ok.
